language: objective-c
osx_image: xcode10.1
install:
  - bundle install
script:
  - bundle exec fastlane tests
deploy:
  provider: script
  script: bundle exec fastlane release
  on:
    branch: master