# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

podspec_name = "PTV.podspec"

platform :ios do
  lane :tests do
    run_tests(scheme: "SwiftPTVTests")
  end

  lane :release do
    pod_lib_lint
    version = version_bump_podspec(path: podspec_name)
    git_add(path: podspec_name)
    git_commit(path: [podspec_name], message: "#{version} release [ci skip]")
    add_git_tag(tag: "#{version}")
    sh("git", "push", "origin", "HEAD:master", "--tags")
    pod_push(allow_warnings: true)
  end
end
